### PR TITLE
Military loot and class changes

### PR DESCRIPTION
**Pull request by bchawke**
These are the proposed changes based on the discussion in #713 as well as skigoggles' proposed changes.  Not sure if I have the syntax correct in the building classes.  Please take a look.

**Change log for this pull request**

New military class created: "MilitaryLow".  These buildings were moved from "Military" to "MilitaryLow":

- Land_a_stationhouse: http://i.imgur.com/12PRXsJ.jpg
- Land_Mil_ControlTower: http://i.imgur.com/vn5zfZ2.jpg
- Land_A_TVTower_Base: http://i.imgur.com/8zpYpu9.jpg
- Land_Mil_House: http://i.imgur.com/fesgWa0.jpg

The “MilitaryLow” class has the same weapon spawns as “Military” with the following exceptions.  These weapons have been removed from “MilitaryLow” class buildings:

- M4A1
- AKM
- G17
- SA58
- M16A4

The spawn rate of these weapons/items in “MilitaryLow” have been changed (spawn rate):
- M16A2 – (from 2 to 0.5)
- AK74 – (from 3 to 0.5)
- AK74U – (from 3 to 1)
- AttachGeneric – (from 4 to 0.5)

These weapons have been added to “Military” (spawn rate):
- G36C – (0.5)
- RPK74 – (0.2)

These weapons have been added to “MilitarySpecial” (barracks) (spawn rate):
- M249 - (0.8)
- L85 Holo - (0.5)
- FAL - (0.5)
- SVD - (0.5)

The spawn rate of 24 slot backpacks have been swapped:
- Czech Backpack - (from 1 to 0.5)
- Coyote Backpack - (from 0.5 to 1)

Spawn rate of Western optics raised in Attachments.hpp
- CCO – (from 1.5 to 1.75)
- Holo – (from 1 to 1.5)
- ACOG – (from 0.5 to 0.75)

### CODE REVIEW

**Comment by bchawke** [comment]
Forgot to add rangefinders to barracks.  I can update tomorrow.

**Comment by thcNox** [comment]
So m14, L110, SVD, and rangefinders added to barracks? some increased values for attachements and I think you removed the pipebomb?

**Comment by thcNox** [comment]
I think you ought to make a comprehensive change log for this if you want peoples opinions.

**Comment by bchawke** [comment]
Yes, M14 (or FAL if people would prefer), L110, and SVD added to barracks at very low drop rates, as well as L85.  Bumped up both the drop rate of AttachWestern in barracks as well as the chance of the attachments being optics in Attachments.hpp.  I did not remove pipebomb, it's still there at it's usual 0.5 drop rate. The intention with attachments changes is to make Barracks be the go-to place for Russian *and* Western optics.  It would bring value back to NWAF by a means other than spawning top tier weapons at a high rate (let's be honest, a 0.2 drop rate of M14/L110/SVD means people will rarely ever see them there).

I added the MilitaryLow class, converted appropriate buildings to MilitaryLow as per @skigoggles ' recommendation, and made a couple of changes to Military class.  Ski made a spreadsheet of the changes that he submitted to you guys.  I contacted him to send me the spreadsheet so I could add the alterations I made then post that as it's an easy way to view what was changed.  I can also type up a changelog.  Any preferred format?  Emulate the changelogs for patch updates?

**Comment by bchawke** [comment]
Just added rangefinders and very slightly upped the Czech and Coyote pack spawn rates.  rangefinders show up as Loot_WEAPON at crashsites, I entered it as Loot_TOOL in the barracks.  Is this correct?

I can make a changelog this weekend.

**Comment by R4Z0R49** [comment]
ok so ill have to double check but it seems you added millLow(Land_a_stationhouse, Land_Mil_ControlTower, Land_A_TVTower_Base, Land_Mil_House) and changed a few of the buildings to use this loot table, but i'm not seeing any changes to the barracks loot table only a few other mill areas like the camps.

if i'm not mistaken barracks is MilitarySpecial.

EDIT, Managed to look over this today all seems to be correct.

**Comment by AsFoxy** [comment]
Are you kidding me? M14 in firestations again?

**Comment by R4Z0R49** [comment]
ok so had a chance this morning to compare the differences. These are the changes

Military = (0.5,G36C_DZ),(0.2,RPK74_DZ)
MilitarySpecial = (0.5,L85_Holo_DZ),(0.2,L110A1_DZ),(0.2,M14_DZ),(0.2,SVD_DZ),((6,AttachmentsWest)TO(7,AttachmentsWest)),(0.5,Binocular_Vector),((1,DZ_BP_Czech)TO(1.2,DZ_BP_Czech)),((0.5,DZ_BP_Coyote}TO(0.8,DZ_BP_Coyote))

**Comment by bchawke** [comment]
M14 was added to Militaryspecial.  Last time I checked fire stations weren't in the Militaryspecial class @AsFoxy .

**Comment by thcNox** [comment]
It's overkill. I'm strongly against m14's spawning in barracks, even without the m14 it's too much. Increasing optics, increasing 24 slot backpacks drops and adding high tier weapons. I'd say pick one of the three.

**Comment by bchawke** [comment]
With a .2 spawn rate you'll be lucky to see more than one or two M14s in the barracks in a year game play.    It will hardly change the weapon economy at all.  The idea behind the edits was to change enough to give players incentive to go there while not having a significant impact on weapon economy.  The 1.8.6 and prior mentality was "I'm going to loot barracks because I'm going to find a top tier weapon".  The intended mentality here is "I'm going to loot barracks because I _**might**_ have a _**slight**_ chance of finding a top tier weapon".  A vast majority of the time they won't, but it's that .2 spawn rate that keeps them coming back.

That's in regard to the weapon additions.  As far as attachments and backpacks, I don't feel it's overkill at all.  Barracks are the *top* military loot spawn building in the game.  Players go there expecting to find something really good, something _better_ than what they can get elsewhere on the map.  Currently they aren't (with the exception of the very rare backpack, Western attachment, or satchel charge spawn).

**Comment by thcNox** [comment]
even with .2 you'd see probably close to a hundred m14's a year being entered into the economy from barracks alone. Probably more than that as my quick assesment is based upon studying satchel drop rates in a patch when few farm barracks. That will of course change dramatically with these changes.

As for barracks being the "top military loot spawn" we disagree. Devs made a conscious decision in 1.8.7 to move away from a barrack centric military loot economy in favor of helicrashes in attempt to break the age old problem with airfields and surrounding areas being the only focus on the map. Your suggestion goes a long in cancelling out that design. People are lazy and will revert to hounding the airfields and folks roaming the map will decrease.

**Comment by bchawke** [comment]
I said "Barracks are the top military loot spawn **_building_** in the game".  That's separate from the random event heli crashes.

As for the decision to move away from a barrack centric military loot economy, I and many players feel it's a bad one, which is why we're stepping up and attempting to make changes to bring value back to NWAF.  This suggestion is a middle ground between 1.8.6 and 1.8.7 (erring much more towards 1.8.7, by the way).  It's a compromise.  Considering it will be much easier to find an M14 at a crash site than the barracks, I disagree with your assessment that people will revert to hounding the airfields.  Trust me, people will roam the map to find Western sniper rifles, Western LMGs, FALs,  G36A/K, and NVGs.

Remember, simply spreading people out ≠ good game design.  Look at DayZ Standalone.  The focus on NWAF is not an "age old problem".  It was actually one of the best design features of DayZ Mod.  It created a natural flow of players from SE to NW and makes it so that even on a low population server you have decent chances of player encounters in that area.  The devs have succeeded in moving away from barrack centric military loot economy, and it has been detrimental to the game (for details on how, read my comments on issue #713 ).  A better approach would have been a less drastic change in balance, simply reducing the barracks' importance rather than virtually removing it.  The changes I have proposed aim to do just this, so that heli crash importance is still greater and players will have more incentive to roam the map, but that NWAF still retains value and will attract players.

**Comment by Brockerino** [comment]
I strongly agree with @bchawke suggestions, the only thing I'd change is the SVD in the barracks, I feel the SVD is on par with the DMR and should be exclusive to crash sites. Other than that, I feel its the change needed to breath life into the NWAF once again.

**Comment by Streatman** [comment]
i have to say it is realy funny...
ppl crying in europa discord and dayz mod discord about how ridiculous basebuilding is, because ppl build one at the airfield and just camp everything, and u guys are still suggesting such a change?

this will literaly only favor ppl that camp there 24/7 and kill everything that comes closer then 100m to the airfieldwalls.

having all the high tier stuff at crashsides made camping at the airfield less efficient then in the past and players still cry about campers there and u want to go back to that?....

im sorry but thats just **Stupid**

**Comment by thcNox** [comment]
I'd rather have you make a convincing argument instead of telling me to trust you as you have given me little to no reason to do so. 

I think you vastly underestimates the changes you have made, either from ignorance or judging by your comments I wonder if perhaps you're intentionally downplaying their importance as to bring back the glory days of NWAF camp fest. 

This smacks more of child in a candy store having a go rather than a measured and carefully thought out suggestion

**Comment by Landbergaren** [comment]
Except the obvious of outscaling weapon economy in this suggestion I also dont like that you want to change the ACOG/CCO ratio. 
I dont mind you making attachements easier to find. But there was no issues with the ratio between finding a cco and a ACOG. ACOG was raised 50% and cco less then 20%. 
A more fitting number for the ACOG chance in loot table would be 0.6

**Comment by bchawke** [comment]
How about we keep insults out of the conversation?  Calling people who are making an effort to contribute to the game stupid, ignorant, and childish is hardly the way to grow the community.  Streatman, base building is a different topic entirely.  The issues with base building should not be solved by drastically reducing the value of the barracks.  Nox, you and I fundamentally disagree how the game should work.  I've made plenty of convincing arguments, you have elected to ignore them.  I put a lot of thought into the changes I submitted and have been very candid about what role I think NWAF and the barracks should have.  I've made my case in #713 .  I'll leave it at that.

**Comment by KPanicEKS** [comment]
Just adding my 2 cents..

I've been playing the mod since the early days (June 2012) and gotta say
the barracks are simply not worth the effort in their current state.. The
problem with putting all the high end weapons at crash sites only is that
the groups with the helis just wait til server reboot and hit all the
crashes within the first 20 minutes of reboot which only makes the strong
groups only stronger. When balancing a game you should be looking at ways
to benefit the entire playerbase, otherwise you are just making the game
more challenging for those that aren't fortunte to have a vehicle or heli
at server reset. Adding in a small chance for high end loot at the barracks
brings the game back to the roots that will make the barracks worth looting
again; but most importantly, gives the better opportunity for the random
players to get good gear on a more consistent basis instead of just after
server restart.

Unless you change the heli crash spawn system so that they aren't spawned
in immediately after server reboot, adding high end loot back to the
barracks makes sense from a game design perspective.

**Comment by R4Z0R49** [comment]
Crashsites are not spawned in on server restart they spawn over time. This has been the same for a very long time now.

**Comment by KPanicEKS** [comment]
how many are spawning in at reboot? 3? then another chance for 2 every hour
on the hour...

that's not random.

**Comment by R4Z0R49** [comment]
1 on start then once every 30-45 mins

**Comment by KPanicEKS** [comment]
Then 1 is too many.. If it's a predicable event (even at 1) every team that
has a heli is out to get that single crash site on reboot and in most cases
will get it. Period.

**Comment by R4Z0R49** [comment]
having 4 barracks with good loot will give 3 more chances to get good loot then the current 1 crashsite.

Anyone with a vehicle will head to static points over a random point every time.

**Comment by KPanicEKS** [comment]
Exactly... Which gives the entire player base a chance at getting good
loot. not just the fortunate ones with a heli.

Set the spawn rates extremely low if you have to. The point is giving on
foot players at a chance for good loot too.

**Comment by R4Z0R49** [comment]
Your argument is fine but i think its directed towards the wrong ppl we haven't said it doesn't need changing. I only corrected you on crash sites.

However i'm not convinced the only way to achieve what we need is by dropping high end loot back in barracks.

If fact we have been very clear with that a change is needed. The question is what change really. The only ideas we get back is buff the barracks lower other mill points hence the pull request.

**Comment by bchawke** [comment]
Perhaps this is a separate issue that needs to be brought up on its own, but I don't believe heli crash spawns are working the way they're supposed to based on what you are describing. The times I have been playing with the group and we have a helicopter, we've found up to three crashes very shortly after restart (definitely sooner than what would be required based on your comment of the 30 to 45 minutes spread).

**Comment by R4Z0R49** [comment]
Admins have control over it.

**Comment by KPanicEKS** [comment]
My apologies, I intended my statements to be for the general forum and not
directly to you.  I didn't know the specifics of the numbers behind the
system and was just going off what's been perceived. Thanks for posting the
actual numbers.

And to be clear, no system is prefect..  but as long as we are identifying
the shortcomings of the current implementation and keeping an unbiased and
open mind when coming up with solutions we are making progress. The beauty
of software development is that nothing is ever set in stone. We have the
ability to make changes, playtest... wash. rinse. and repeat until we get
it right...

**Comment by Streatman** [comment]
i havent called u stupid @bchawke 
but i called the idea of only buffing baraks stupid

but as i said, i am fine with changing attachments

**Comment by R4Z0R49** [comment]
We are all in agreement something needs to change the question is what/how.

**Comment by Streatman** [comment]
i think the best way would be to work out a system were baraks and helicrashes both have to be looted to get high end stuff, like getting the m24 rifle with ironsight from crash and get the scope from the baraks

same with other guns

and that all while crashside should always be the supperior lootspot cuz otherwhise the NWAF will just become a camping fest again

**Comment by knightmedic** [comment]
My thoughts is that the mod is dying. Less and less people are wanting to play due to a number of reasons. I play with a squad on a server and there are times where we will spend hours and days without seeing someone. There is no reason for people to go north anymore due to lack of gear in barracks and most crash sites. I completely agree with what bchawke is saying. I also think base building needs to go because from what I've seen all people do is put a base in a mid to high traffic area and shoot people that come near, which in return will make people quit going to those areas.

**Comment by KPanicEKS** [comment]
The system you've outlined still ignores the fact that teams with helis are
the ones that usually get to the crash sites first. What good is an
attachment if you don't have a good weapon to put it on?!

If a system like that was put into the game then put the attachments at the
crash sites and the guns at the barracks so ground forces have a fighting
chance with the better equip groups. But I'm still hesitant to suggest a
system as you've outlined as it still doesn't resolve the issues with teams
with helis getting to crash sites first... That is the crux of this issue.

**Comment by Streatman** [comment]
well, groups with helis will always have the advantage, doesnt matter if searching helicrashes or camping the airfield

and its fine, its realistic that ppl that play together have the advantage.
i never saw an apocalyptic scenario were lonewolfs were godlike or in favor against a squad

and if the helisearch is the biggest problem in your eyes, then make a pull request for "removing helicopters from the game" that will solve your issues but will also take a big part of the game away

EDIT: actualy i am talking with my friends over this topic now, and they have the solution to the "heli-problem"... just make fuel even more rare

**Comment by KPanicEKS** [comment]
The beauty of video games are that they don't have to mimic real life 1:1.

The point of my conversation is improve the balance of loot and who's
getting it. Rewarding the players that already have an advantage is
intrinsically faltered and should be avoided when attempting to balance
gameplay in any game, not just DayzMod...

**Comment by Jbird206** [comment]
Just wanted to add my two cents. As a recent server owner, I've done a bit of testing with loot spawns. Barrack spawns are way too meager and are pretty much parallel to fire stations ATM. What is the point of traveling to airfields just to get an ak74? In placing 6 barracks side by side they might at most, spawn 3 low level rifles and some random item like an herb box. Same goes with crash sites. More ak74U's and camp netting. Hangars are completely awful as of now. I have read the proposed changes and wish spawn rates/types were increased even more.

**Comment by GeryonTom** [comment]
Okay my 2 cents.  Barrack's should be where end game loot ought to be.  It allows a consistent location for the gear with a the added risk of dying (due to high traffic) and having to run back to what is the farthest location on the map worth going.  Heli-crashes should be considered an unusual event.  Maybe even make them rarer or limit to one crash per restart.  The gear in heli crashes should be equal to the barracks.

Since the barracks don't contain high end gear people simply don't go there anymore.  Why bother making the trek up north for mid-tier gear?  Instead you can game the system and route your player to several open fields to look for the high end gear.  This results in players having a much harder time finding each other as they walk through their own heli routes.

**Comment by bchawke** [comment]
Thanks for the insight @GeryonTom .  I _do_ feel that some highly coveted items such as DMR, M24/M40A3, NVGs, M240/Mk48, and FAL/FAL_ANPVS4 should be exclusive to crash sites.

**Comment by KPanicEKS** [comment]
But why? I strongly feel that limiting the best loot to crash sites is
still rewarding players that have a vehicle advantage at reboot. If you
want to fix that mechanic then make it so crash sites dont spawn at reboot
and only happen periodically at random times throughout the entire course
of the server uptime. It needs to a truly random event to keep it even
across the board.

and since we sorta breached the subject... the crash site system could use
some changes too. e.g., spawning zed when the crash site spawns and keeping
them contained within a given diameter around the crash site (regardless of
the 300m proximity to players) Currently it's too easy to see if a crash
site is a threat or not. If there were zombies at the crash sites
regardless of player proximity then they would be a bigger threat to all
and much less predicable. Again though, that discussion is outside the
scope of this issue and should be discussed in a separate thread.

**Comment by bchawke** [comment]
@M0tzilla I agree with your suggestion that heli crashes are not spawned at server restart.  I think starting a new issue to discuss the intricacies of heli crashes would be good.

**Comment by bchawke** [comment]
Changelog has been added to pull request.  Also, I was thinking about adding these buildings to "MilitaryLow" as well:

- CampEast: http://i.imgur.com/RmU5YDZ.jpg
- CampEast_EP1: http://i.imgur.com/IP25yQb.jpg
- Land_tent_east: http://i.imgur.com/ODt4pA2.jpg
- C130J_wreck_EP1: http://i.imgur.com/yc2p9Qx.png

This would move most (all?) of the "Military" class loot away from the coast which would mean primarily "MilitaryLow" weapons such as SMGs, shotguns, and low tier assault rifles.

**Comment by R4Z0R49** [comment]
Thanks for adding the change log.

I hope you guys now realise how hard these desisions are to make with such a difference in the player base and the reason we have to have so many global settings for admins.

**Comment by thcNox** [comment]
I'm all for removing military loot from the coast and I like the new military low however removing military loot from the military tents is not ideal as those tents are used all over the map and not just the coast. I'd rather remove the tents at the coast than nerf the loot in them.

**Comment by skigoggles** [comment]
against my better judgement, I'll jump back in. This discussion started with some small changes to the military_special class and a new military_low class (firehouse+atc+greenmtn/balota carport building).  

Changing the tents/camp/c130 was not part of the original discussion that I started.

We can all agree that even small changes can have big player/gameplay impact, so I'd like to get this back to a _small_ set of changes.  The format is a spreadsheet, so not conducive to this forum.  I can share my original thought with whoever wants them - I can upload it to a discord channel later this evening.

**Comment by bchawke** [comment]
To be fair, skigoggles, the only weapon change I made to your suggestions for MilitarySpecial was adding the L110A at .2.  I also raised Western attachment spawn rate and added rangefinders which most people seem to be fine with.  Not sure what peoples' thoughts are on backpack spawn rate changes.

As for the additional MilitaryLow buildings, while it's a less subtle change, I know that many people have advocated for removing mid-tier military loot from the coast and I feel this would be the way to achieve that goal.  I'm not really worried about the impact on the tents and C130 inland at other locations because those are in close proximity to plenty of Military class tents and barracks.  With the current four buildings that have changed, people will simply bypass them and run to the tents and C130 on the coast to get the mid-tier loot.  Either way, it's just a suggestion.

Since people have brought up the intention of making smaller changes as opposed to larger ones, let me point out that the 1.8.6 -> 1.8.7 loot table changes for barracks were _**massive**_ and have had a huge impact on gameplay (some of it for the better but a lot of it for the worse).  The entire point of my changes is to come up with a compromise between the two.  I am the one advocating for smaller changes with this pull request.

I was going to upload Imgur links to the spreadsheet skigoggles made and the one that I altered, but Imgur is down right now.  I'll upload for reference later.

**Comment by bchawke** [comment]
Updated changelog with mention of added rangefinders and updated backpack spawn rates.

**Comment by bchawke** [comment]
Here's an image of the spreadsheet skigoggles came up with: http://i.imgur.com/ahw5tM7.png

Here's the same spreadsheet with my changes added to it: http://i.imgur.com/0qpqoq9.png

Even though we differ on the amount of changes, BIG props to @skigoggles for coming up with the outline for adding the new military class!

**Comment by thcNox** [comment]
Well @skigoggles I think your loot table is a good starting off point. I'm still not fond of the M14 in the barracks. At 0.2  spawn rate these will largely really only end up in the hands of squads who loot cycle the airfields or people who only log in at night to loot cycle with no one else on. In comparison the satchel charge has 0.5 spawn rate and we still hear people complaining they've never found one. So believe the only thing you will achieve is that more high end guns will end up in circulation among the no life veteran crews who already have gear with few exceptions. A rough suggestion from me would be to replace the M14 in the barracks with a M249 with a spawn rate at around .8 or 1 and bump up the SVD to .5.  

The M249 is a 5.56 machine gun which I believe will be widely appreciated but still has a lesser impact overall than the M14 which means it can be placed at a higher spawn rate which in turn makes the loot experience for the average player more rewarding. The SVD remains as a rare but sought after item just like the satchel charge but unlike the satchel that pretty much has a singular use  the SVD's functionality probably appeals to a larger group of players.

**Comment by Brockerino** [comment]
@thcNox what about swapping out the m14 for a FAL at .5 spawn rate?

**Comment by thcNox** [comment]
@Brockerino Certainly better than having the m14 yes. I believe FAL i slightly inferior to M14 in specs and magazines for it are harder to come by. I would still argue that you would want to add something like the SAW at a higher spawn rate that would make barracks more attractive for people that don't loot cycle for hours. but again gotta be careful to not over do it but it's an option for sure to add all three (M249, FAL, SVD) on the high tier gun front.

**Comment by bchawke** [comment]
Nice.  Pretty much exactly my weapon suggestions but with higher spawn rates.  Glad we're finally seeing some common ground.  So, just for clarity...

My changes:

- L110A – (0.2)
- L85 Holo – (0.5)
- M14 (or FAL) – (0.2)
- SVD – (0.2)

Current suggestion:

- M249 - (0.8)
- L85 Holo - (0.5)
- FAL - (0.5)
- SVD - (0.5)

I'll go ahead and update the code and commit.  Seeing as the high tier weapons have the biggest impact out of the proposed changes, I'm guessing that there's room to go either way on attachments/rangefinders/backpacks.  I'll bump Western attachments back down to 6.  I'd still like to see backpacks a bit more common but if people simply can't live with it I can bump them back down to 1.8.7 levels.  Where does that leave us on rangefinders?

**Comment by bchawke** [comment]
Change log updated to reflect most recent commit.

**Comment by thcNox** [comment]
In the hawke suggestion I would leave backpack, attachments and clothing alone (1.8.7). Remove rangefinders  Also probably leave FAL out to be on safe side.

Also flipping the spawn rates for coyote and czech backpack have always made more sense to me, czech probably being most desirable backpack. So 1 for coyote and 0.5 for czech. But it's bit subjective.

**Comment by Brockerino** [comment]
Let's meet in the middle.  Leave the fal, revert backpacks/attachments to current levels.

**Comment by bchawke** [comment]
Okay.  I'll reduce backpacks and swap Czech/Coyote rates and remove rangefinders.  Barracks attachment spawns were already reverted to 1.8.8 levels.  I didn't make any changes to clothing.

**Comment by bchawke** [comment]
Change log updated.

**Comment by thcNox** [comment]
@Brockerino Much better and less destructive to end up doing too little than too much. After a few months on live you can reevaluate the impact of the changes. And make a new pull-request to discuss further actions. Even without the FAL there's a lot of changes here. The more changes you make the harder it becomes to predict the result. Even if you know you want to end up at certain point it's much more sensible to get to that point in controlled steps rather than large uncertain leaps.

**Comment by bchawke** [comment]
Agreed.  After the giant leap from 1.8.6 to 1.8.7 loot levels, we are taking what is relatively a very small step back towards 1.8.6.  I think the impact will be positive.  I can't wait to see how skigoggles' new military class affects the coast.  I believe it will also make a positive impact.

**Comment by thcNox** [comment]
I think it's important to note that you don't have to go all way back to 1.8.6. levels to effectively get the same sort of situation we had at the NWAF back then so really what's important to focus on is what sort of impact these changes will have. How close they are to the levels seen in 1.8.6 is largely irrelevant.

**Comment by Duraikan** [comment]
The changes look great!

**Comment by Borges80** [comment]
Here's my take. First off thanks to BC for taking the time to do this.
**Cons:**
It will be much harder to acquire mid-tier military weapons with the current rate and firestations/atc's etc will be pretty bad everywhere, especially with those spawn rates for "militarylow" weapons. I suggest bumping the "militarylow" spawn rates just a tad higher.

M16A2 – (from 2 to 0.5) - Change from 2 to 1
AK74 – (from 3 to 0.5) - Change from 3 to 1.5
AK74U – (from 3 to 1) -Change from 3 to 1.5
AttachGeneric – (from 4 to 0.5) - Change from 4 to 2. 


M249 - (0.8)
L85 Holo - (0.5)
**These should be swapped. An LMG shouldn't be more common than an AR.**

The spawn rate of 24 slot backpacks have been swapped:
Czech Backpack - (from 1 to 0.5)
Coyote Backpack - (from 0.5 to 1)

**Disagree with that completely. That should either be reversed or made the same value since coyote can hold more weapons than czech. Same value will be both at 1 which is fair. 0.5 is way too rare.**

**Pros** I think the barrack changes are perfect imo. It will definitely give you more incentive to go to barracks and even NWAF with the possibility of these weapons cause as of now they're completely useless. I don't even bother with barracks anymore.

I like the new "militarylowclass". This could actually be awesome to gameplay limiting the amount of camping on the coast and people will rely more on farm/residential weapons as fresh spawns. Will make things much more interesting, however as I said I think the spawn rates were dropped way too low. A number of weapons have already been removed and crashing the spawn rates that much will make these locations useless in general. 



CCO – (from 1.5 to 1.75)
Holo – (from 1 to 1.5)
ACOG – (from 0.5 to 0.75) These look great.

**Comment by thcNox** [comment]
>It will be much harder to acquire mid-tier military weapons with the current rate and firestations/atc's etc will be pretty bad everywhere, especially with those spawn rates for "militarylow" weapons.

That's the whole point...You shouldn't acquire mid-tier military weapons at the coast.

> I suggest bumping the "militarylow" spawn rates just a tad higher.

Increases values by 50% or more is not what I call "a tad higher"

>These should be swapped. An LMG shouldn't be more common than an AR.

I don't buy this piece of logic at all.

>Disagree with that completely. That should either be reversed or made the same value since coyote can hold more weapons than czech. Same value will be both at 1 which is fair. 0.5 is way too rare.

The fact that the coyote can hold more weapons is something the majority of the player base doesn't even know about. the Czech is generally more valued for it's tactical advantage of being camo.

**Comment by Duraikan** [comment]
I have never heard of anyone that prefers the Czech over the coyote simply for camo.  Most people I know like the Coyote better because it is much lower profile.

**Comment by thcNox** [comment]
Coyote is a bright shining target in the forest.

**Comment by Streatman** [comment]
Coyote can also carry 2 mainweapons, the czechbackpack only one
Coyote provides a clear sight when u want to watch behind you (1st person of course) and czech backpack doesnt... that is the biggest downside to a czech on our server and most important for us
so Coyote is in fact better then a Czech one but some ppl have other favorites just like i think that the DMR is garbage and the SVD the best sniper there is
@thcNox

**Comment by thcNox** [comment]
Yes it's bit subjective as I noted earlier. Everyone I play with value the czech over the coyote except a few heroes that prefer coyote for the looks. Also I'm pretty sure you can fit two 10 slot weapons in the czech as well.

**Comment by Streatman** [comment]
yeah i usualy only run around with 1 weapon in general so i dont know 100%,
but the ppl that care about camoflage are also usualy the ppl that use a ghilli most of the time and that is the skin were it doesnt matter
so i would vote for leaving it like it is

**Comment by Borges1091** [comment]
> It will be much harder to acquire mid-tier military weapons with the current rate and firestations/atc's etc will be pretty bad everywhere, especially with those spawn rates for "militarylow" weapons.
That's the whole point...You shouldn't acquire mid-tier military weapons at the 


> I suggest bumping the "militarylow" spawn rates just a tad higher.
Increases values by 50% or more is not what I call "a tad higher"

> These should be swapped. An LMG shouldn't be more common than an AR.
I don't buy this piece of logic at all.

> Disagree with that completely. That should either be reversed or made the same value since coyote can hold more weapons than czech. Same value will be both at 1 which is fair. 0.5 is way too rare.
The fact that the coyote can hold more weapons is something the majority of the player base doesn't even know about. the Czech is generally more valued for it's tactical advantage of being camo.

Well since you disagreed with every single one of my suggestions how about some feedback for each one. 50% bump from BC's values, seeing how he drops the values by 150-250% which is pretty insane. I think i'd be better to make them harder to get but not impossible.

You don't buy the logic of how an LMG should be rarer than an AR? Why? They both shoot stanag. They can both be fitted with attachments. One has a fire rate triple the other, and 6x the ammo capacity. Explain the illogical reasoning behind making an AR rarer than an LMG.

Czech pack is camo yes that's a plus but it's also a trailer on your back making it extremely easy to see anyways, and worse for moving around weapons.

**Pull request closed without merging**
