### PR TITLE
Update transfusion.sqf

### PR DESCRIPTION
**Pull request by Veltro-pm**
24 Dec 2014 (Veltro): Addapted code to work for blood bags and whole blood bags. Removed the use of uninitialized variable '_bbselect'. Rearranged arrays to optimize blood bag selection. No longer treat someone that has an unknown blood type as type O-. Small optimization to humanity points that are awarded (mainly less points in case of treating a healthy person). Improved program flow for better readability.

### CODE REVIEW

**Comment by Veltro-pm** [comment]
If you tell me the rules that apply to the blood enzyme, I can have another look if something should work different.
"update transferred script to match change"
not sure what that means, do I need to do something?

**Comment by R4Z0R49** [comment]
Sorry just got home. Transfusion has two parts the player sending the info and the player receiving the info. You have updated the player sending the blood really this hole system needs to be redone rather then just adding to it.

What needs to happen
Player 1 starts transfusion of full bloodbag(12000) this then starts the loop for that player during that loop send info to the receiving player to say start a loop and consume the blood being given. Both players need to have a loop going so both players get notices on whats happening during the transfusion 

4000k blood bags should not be used for this as the 4k ones are self made they are not found. However there is no reason players cant make a water+salt(saline bag) salinebag maybe containing 2k/3k/4k that they can give to another player. (if you make the saline bag just make sure its not too easy to make (boiled water, Broke down salt(maybe from the sea), emptybag, transfusion kit). You might have to add a limit of how many can be used at one time.

direct blood transfusion isnt possible due to the blood not being a 100% match you will need to look all that info up for the whys but blood given from a hospital has a enzyme(or something cant remember the exact item) in it that helps with compatibility. We was trying to mimic real life for the blood system.

I'm going to start on the arma 3 version (A3PSF) of medical transfer next week so ill try and get that system redesigned to work on arma 2 as well.

**Comment by Veltro-pm** [comment]
Yeah, uhu, that is all wonderful, but I just want the script to be fixed ASAP because it is entirely broken. We should not spend time on making changes right now, that comes afterwards. I don't see any reason why a whole blood can't be transfused. Whole blood is the exact same thing as red blood cells however it contains plasma and the same rules apply in case you wish to implement this 'realistically'. Maybe in that case there is a higher risk because blood may 'clutter' or may cause 'transfusion associated circulatory overload' (TACO) (for which reason I thought whole blood bags had only 4k blood because TACO can be prevented by adding blood slowly and only little bits every time). As a matter of fact, it is not even clear why a player would not be able to apply a 12k blood bag to himself while being able to apply a whole blood. This doesn't make any sense! The only thing I did is look at the code because transfusion is broken and I was amazed how many things in the code didn't make any sense, so I rewrote it. Please just implement it and make everybody happy. Of course we may have to look at the client side script as well, however I did not change anything in the communication. I did add a "TO DO" there because I don't understand why 'publicVariableServer' command is executed so many times (4 to 12 times more then necessary I think). Next time just meet someone on Skype if he proposes that because discussing this in this manner just doesn't work. The script should be simple: Player applies blood bag -> transfusion kit and blood bag consumed -> blood is given to receiving player if blood bag is compatible - > consequences to receiving player if player gave wrong blood bag. Nothing more!

**Comment by R4Z0R49** [comment]
ok thanks for your effort anyway.

**Comment by Veltro-pm** [comment]
Hi Carl, thanks for your response. It sounds like this is something that you can't address right now, so I would like to provide you more details as to why the script is not working, so that we can fix this together if you want.
The problem is at Line 116 (v1.8.3): _bbselect is uninitialized. (Script aborts at line 178 because _forceClose = true).
The reason for that is because the code block on line 64-69 (v1.8.2) was changed into line 58-59 (v1.8.3).
Besides that I found that line 25 and line 128-131 (v.1.8.3.) provide unwanted results or are erroneous.
I have proposed some changes to the script that address most of this. If you decide not to use it, that is fine, but then is it possible to please revert this script to v1.8.2. to fix the problems for now, so that transfusion will work again in v1.8.4?
Thanks for your time and I am sorry to have bothered you on Christmas day. Happy Holidays to you and your loved ones.

**Comment by Veltro-pm** [comment]
oh, when I referred to v1.8.3. I actually ment the version that is in the development branch right now, sorry for that.

**Comment by R4Z0R49** [comment]
The issue your referring to isnt the original issue we had. The missing var is a change made before 1.8.3 came out. The issue prior to that was the over used PVS and call re's. If you look in the self blood bag script you will find the missing var. 

_bbarray_length = (count _bloodBagArrayNeeded) - 1;
for "_q" from 0 to _bbarray_length do {
    _bbselect = _bloodBagArrayNeeded select _q;
    _bloodBagNeeded = _bbselect in magazines player;
        if (_bloodBagNeeded) exitWith {_BBneeded = true;};
};

Change it to that and the script will work again but on full servers it will crap out due to the over used PVS and call re calls they need to be reduced.

i'm out till after xmas now.

**Comment by R4Z0R49** [comment]
k added an untested change to the bloodbag system

https://github.com/DayZMod/DayZ/commit/c74336212ad0fb4f1f84775f8fe7c46ac1c68507

Needs testing, ps also added your humanity limit change

**Comment by Veltro-pm** [comment]
Ok, fixing '_bbselect' looks great.
One problem with this code is still that the correct blood bag may be applied and causing a fainting player. So let's say a player has A+ and the medic applies A+ the player will faint because no blood test has been done.
I have finallized my pull request which deals with that and it now also reflects your changes. I made applying a whole blood bag optional since you didn't want that.
I hope it will be usefull to you.

**Comment by R4Z0R49** [comment]
I see that as more of a penalty for not knowing your blood type. But thanks for now lets get it working and ill look at that again later on when i bring in a real select system for blood.

We still need to get it all tested to make sure its working as it should be

**Comment by R4Z0R49** [comment]
Request closed, Moved relevant parts over to the new script. Credits updated.

**Pull request closed without merging**
