### PR TITLE
add stashes to exclusions

### PR DESCRIPTION
**Pull request by wriley**

### CODE REVIEW

**Comment by Skaronator** [comment]
Well, there is more missing visit #30 for more information.

**Comment by wriley** [comment]
OK, I fail at searching. :)

**Comment by Skaronator** [comment]
np man ;)

**Comment by wriley** [comment]
I added Skaronator's fix for pCleanup from #30 with table name case updated. Case is important on pretty much any OS but Windows. My hive database is on Linux MySQL so is case sensitive.

**Comment by thevisad** [comment]
FYI, case sensitivity is not an issue if the MySQL server is properly installed on Linux. I run a mix of MySQL linux vs windows servers and have zero issue with any case sensitivity issues. http://enricogi.blogspot.com/2008/05/mysql-case-sensitive-in-linux.html

**Comment by wriley** [comment]
There is that workaround but being a *nix sysadmin for 20 years has put me in the habit of using the correct case. :)

**Pull request closed without merging**
