### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abarichello**
Updated readme,
ordered contributions alphabetically, removed duplicates and fixed broken links formatting.

### CODE REVIEW

**Comment by skigoggles** [comment]
maybe I'm reading github wrong, but your contribution seems to be to add comments to the readme with your name on the top?!

**Comment by abarichello** [comment]
Names were ordered alphabetically, if the maintaners feel like that's not a worthy contribution they can remove the name.

**Comment by abarichello** [comment]
You can view the corrected README with fixed ordering, removed repeated names and fixed MarkDown formatting [here](https://github.com/aBARICHELLO/DayZ/blob/32c0bfa34fc9e4a17920ac6e803ea23ee13254e0/README.md)

**Comment by skigoggles** [comment]
you are a troll and I expect this will be appropriately rejected.

**Comment by abarichello** [comment]
Contributors list are most of the time ordered alphabetically, if you feel like anyone on the list deserves higher recognition you can create a new one or add them to the existing special thanks section.

**Comment by icomrade** [comment]
the list, as is, is ordered by quantity of contributions, and should probably just stay that way

**Comment by aBARICHELLO** [comment]
Waiting on maintaner input for changes

**Pull request closed without merging**
