### PR TITLE
Basic Water Barrel System

### PR DESCRIPTION
**Pull request by CoftSock**
ItemEmptyBarrel as magazine > emptybarrel which will turn into waterbarrel after 24 hours then after 5 days waterbarrel will delete.

### CODE REVIEW

**Comment by AlStotz** [comment]
I like the idea of a water barrel... I think they should be placeable,  but
only contain something like 5 water bottle refills... And they refill after
every rain fall. Seems a bit complex... But it would make some nice 'base
deco' that players could further decorate their bases with a point/purpose.

**Comment by CoftSock** [comment]
guess this shit aint getting a gig?

**Comment by AsFoxy** [comment]
So the idea is to use it to collect rainwater? I feel that such access to water at player bases might make them too self-sufficient.

**Comment by CoftSock** [comment]
well yes, the arma system is limited so real tracking of weather will never happen. But the empty barrel will turn into a water Barrel after 24hr and then the water barrel will despawn after 5 days. i feel that can cater for realism. ofcourse the barrel will be a rare spawn in the first place.

**Comment by R4Z0R49** [comment]
im going to leave this active for a bit until we start looking at items inside base's. I like the idea but i feel the same as foxy it will make the bases a bit too self-sufficient.

in its current forum anyway.

**Comment by MulderDayz** [comment]
I like the water barrel idea, it's similar to the permanent fireplace imo which was also a great idea.  However, I don't like the fill with rain idea, it kind of goes against the water boiling and drinking from a safe well.  I think to fit what's in the game already, it should be a permanent fixture that gets places once like a permanent fire place.  I think that you should be able to fill it with water bottles.  If you don't boil the water first you can still get sick from it.  This to me matches other systems in the game.

**Pull request closed without merging**
