### PR TITLE
Implemented car bomb

### PR DESCRIPTION
**Pull request by vmartsynovskyy**
I made this a while ago but at the time the GitHub repo only had .pbo files and wasn't updated.

Here is an example of the car bomb in action: https://www.youtube.com/watch?v=BkglZ5nxyA0
The only thing I've changed since then is that you place the bomb by right clicking on the bomb in your inventory instead of using the action menu on the target vehicle in order to keep the car action menu free of unnecessary clutter.

It currently saves over restart but it uses a system that is a bit of a hack to avoid having to add a column to object_data. The way it saves to the database is it adds a fake item called "BOMB" to the cargo of the vehicle before it is added to the database. This item isn't actually implemented whatsoever and only exists in the database. When the server is adding cargo to the vehicle during spawning from database it checks for the "BOMB" item and if it is in the inventory in the database it sets the variable "hasBomb" to true.

### CODE REVIEW

**Comment by R4Z0R49** [comment]
im still on the fence about adding this. I'll leave it open for other comments.

**Comment by ericandersen** [comment]
Neutral. Sounds cool. 
Neat idea using the inventory to keep clutter out of the DB.

**Comment by vinyljunkie** [comment]
This could add some more tension to the game, I kind of like it.

Is it possible to check for and disarm the bomb as a very cautious survivor?

**Comment by vmartsynovskyy** [comment]
@vinyljunkie Not at the moment but that's very possible to implement. If this gets a bit more traction I might go back and defusal of bombs

**Comment by Lukethero** [comment]
Without a way to diffuse or at the least check if the car has a bomb would lead to some rage enduring deaths and leave the player with the feeling of beeing powerless over their death.

**Comment by R4Z0R49** [comment]
going to lose this as we have no way to see if car is armed or not.

Thanks anyway

**Pull request closed without merging**
